name: Release
on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: buckhamduffy/release-drafter@v1
        with:
          master_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
